services:
  halogen-qwen3.8-flash-next:
    networks:
      - halogen-internal # isolate
    image: ghcr.io/peonist-ai/halogen-flash-server:0.5.6
    devices:
      - /dev/kfd
      - /dev/dri
    security_opt:
      - seccomp:unconfined
    ipc: host
    ulimits:
      memlock: -1
    volumes:
      - $HOME/models/qwen3.8-flash-halogen:/models:ro

  # for direct chat/completion proxy with no litellm proxy
  # I believe there is a bug in litellm that prevents
  # consistent tool output over hosted_vllm
  nginx-openai:
    networks:
      - halogen-internal # so litellm can hit halogen
      - public-inbound
    image: ghcr.io/smart-craw/smart-craw-llm-proxy:v0.6.2
    ports:
      - "8081:8080" # only this is exposed to the host/LAN
    environment:
      BACKEND_SERVICE: http://halogen-qwen3.8-flash-next:8731
    depends_on:
      halogen-qwen3.8-flash-next:
        condition: service_started #healthy

  litellm:
    networks:
      - halogen-internal # so litellm can hit halogen
      - public-inbound
    image: ghcr.io/berriai/litellm:main-stable
    ports:
      - "8080:4000" # only this is exposed to the host/LAN
    volumes:
      - $HOME/service/litellm-config.yml:/app/config.yml
    command: ["--config", "/app/config.yml"]

networks:
  public-inbound:
    driver: bridge
  halogen-internal:
    internal: true
